name: 打包仅供下载arm docker镜像
on:
  workflow_dispatch:

# 只在这里两处修改，一处镜像名、一处标签，其余自动同步
env:
  IMAGE_NAME: xiaomusic
  IMAGE_TAG: 0.6.1

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64]
        include:
          - platform: arm64
            arch: arm64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          context: .
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}

      - name: Test Docker image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} /app/.venv/bin/python3 /app/xiaomusic.py -h

      - name: Export tar package
        run: |
          docker save ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ matrix.platform }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images-${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ matrix.platform }}.tar
          path: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ matrix.platform }}.tar
          retention-days: 90
